### ISSUE TITLE
Suggestion: Switch default version to 0.17.60

### ISSUE THREAD

**Issue by Thue** [KirkMcDonald/kirkmcdonald.github.io#185]
0.17.60 is the stable version that everybody is playing on. I don't think it makes sense to have 0.16.51 be the default version.

**Comment by raiguard** [comment]
Well actually 0.17.79 is the stable version now.

**Comment by Stargateur** [comment]
anyway, time to change the default.

**Comment by DRY411S** [comment]
I have created a pull request that addresses this issue. https://github.com/KirkMcDonald/kirkmcdonald.github.io/pull/198

I *think* that the version number in kirkmcdonad reflects the last recipe change in that version, not the most current version of the game.  Fo example, whilst the latest stable version of the game is 0.17.79, the last recipe change in version 0.17 of factorio, was in 0.17.60, when basic oil processing was changed to produce only petroleum gas. There have been no recipe changes since then. 

(Reference: https://forums.factorio.com/viewtopic.php?f=3&t=73828)

**Comment by Zaflis** [comment]
Agreed, it's weird that it still defaults to 0.16.x recipes that almost noone plays with.

**Comment by Stargateur** [comment]
@Zaflis you mean https://www.factorio.com/blog/post/fff-360 ? you was 7m too early.

**Comment by Zaflis** [comment]
All the more reason to update default game version to kirk, 1.0 is here.

**Comment by KirkMcDonald** [comment]
The calculator has been updated to 1.0.
