### ISSUE TITLE
Vanilla Expensive Advanced Oil Processing, Fluid Consumption

### ISSUE THREAD

**Issue by MarcoMue** [KirkMcDonald/kirkmcdonald.github.io#204]
![image](https://user-images.githubusercontent.com/21143636/92141797-3a697300-ee13-11ea-8d56-0f190b3f3d0e.png)

This shows that i would consume a lot more Fluids then i actually do.

![image](https://user-images.githubusercontent.com/21143636/92141744-2756a300-ee13-11ea-8b3c-1a097d8fd74b.png)
![image](https://user-images.githubusercontent.com/21143636/92141776-3178a180-ee13-11ea-9baa-54382bfe506a.png)

**Comment by DRY411S** [comment]
FYI, the results are identical in Vanilla Normal Mode, since none of the recipes are different in expensive mode.

This isn't a bug in my opinion. The issue here is that the calculator is showing what non-integer refineries and crackers need to produce. But you cannot build non-integer refineries and crackers.

Plastic makers with 5 beacons (10 modules) have a craft speed of 3.05. They each require 61 gas per second. For 16 plastic makers, that's 976 gas per second, 58560 gas per minute). [As shown by the calculator, and being consumed in the game, in your screenshots].

However, you cannot build 3.9 refineries. I assume that you have built 4. That extra 0.1 refinery will be producing extra gas, which means that less of the heavy and light needs to be cracked into gas. Therefore less heavy and light is being consumed in game than the calculator shows.

I presume (but haven't done the maths), that this then has a knock on-effect on the amount of crude per minute being consumed. The 3.9 refineries will be running 100% of the time, consuming the amount of crude that the calculator suggests. But the 4 refineries will not be running 100% of the time due to the excess gas being produced. (4 refineries at that speed will be producing over 1,000 gas per second (including cracking). Your plastic makers will consume less than that, so the refineries won't run all the time.)

**Comment by MarcoMue** [comment]
I am using 0.1 (2.5%) more refineries but im using 7k (22%) more crude oil. This is no rounding error. And if i get the exact raw output but using a different input this seems like a bug.

**Comment by DRY411S** [comment]
It's not a bug.

The 3.9 refineries claimed by the calculator (with the beacons) run at 8.55 speed. So they could consume 40,014 crude per second but the calculator claims that they need only 39,128.038.

So the refineries required is actually 3.9*39128.038/40014 = 3.813648928

3.813648928 refineries at 8.55 speed consumes 3.813648928*8.55*20*60 crude per minute: 39128.038 (exactly what the calculator says):

Because of the 30% productivity bonus they produce (per second):

Light | Heavy | Gas
-- | -- | --
381.50 | 211.94 | 466.28

The crackers run at 6.55 speed. Including the 30% productivity bonus, the heavy to light crackers convert the 381.50 heavy per second, and produces (per second):

Light
--
206.64

The light to gas crackers now have 206.64+381.50 ligt per second to crack. They run at 6.55 speed and achieve a 30% bonus. This translates into gas (per second) of:

Gas
--
509.72

Add this to the gas from the refineries 466.28 and you get 976 per second. _**Or if you prefer 58560 gas per minute from 39,128.038 crude per minute. Which is exactly what the calculator said it would be.**_

Ergo, it's not a bug. But it isn't realistic. because it doesn't use whole numbers for the refineries and crackers.

That's why, when I use the calculator, I take the number of refineries it suggests, round it up to the nearest integer, and do my own calculations for crackers. In this case I would build  4:2:6 and expect the dramatic fall in crude oil consumption that you observed.


Process | Building | Productivity | Craft Speed | Craft Time (s)
-- | -- | -- | -- | --
Advanced Oil Processing | Refinery | 1.30 | 8.55 | 5.00
Heavy to Light Cracking | Chemical Plant | 1.30 | 6.55 | 2.00
Light to Gas Cracking | Chemical Plant | 1.30 | 6.55 | 2.00


Beaconed Ratios | Process | Actual |   |   | Light | Heavy | Gas
-- | -- | -- | -- | -- | -- | -- | --
Number of refineries | Crude Refinery | 3.81 |   |   | 381.50 | 211.94 | 466.28
3.813648928 | Heavy to Light | 1.62 |   |   | 206.64 |   |  
.  | Light to Gas | 5.99 |   |   |   |   | 509.72
  |   |   | Net Fluids per second |   | 588.14 | 211.94 | 976.0

**Comment by DRY411S** [comment]
Having said all the above, the calculator would be better (in my opinion) if it could do the refinery and cracking rounding, and then adjust the crude required downwards.  Whilst that would appear to be straightforward for your example for plastic, it may not be so easy when there re several different oil ouptuts required (lube, sulphur, acid, plastic, explosives, solid fuel, rocket fuel)

**Comment by DRY411S** [comment]
[refinery.zip](https://github.com/KirkMcDonald/kirkmcdonald.github.io/files/5180257/refinery.zip)

^^This attached factorio save, is a 4:2:7 oil build, using the same beacons and modules as your kirk calculator. There are 16 chemical plants making plastic, again using the beacons and productivity modules you used in the calculator.

NO fluids are buffered anywhere. The water and crude oil are created using infinity pipes from the 'editor extensions' mod, to ensure that the flow is guaranteed.

To load the save you will need to install the [editor extensions mod](https://mods.factorio.com/mod/EditorExtensions)

It produces these stats. Exactly what the calculator say it should be. (Note that there are no stats for crude and water produced, because these are created by the infinity pipes. But you can see that the fluids consumed are the same as the calculator)

![image](https://user-images.githubusercontent.com/19732374/92334819-537b5980-f089-11ea-8f20-3a101fdf7af0.png)
![image](https://user-images.githubusercontent.com/19732374/92334884-d7354600-f089-11ea-9b0c-bf891cac07c5.png)

**Comment by MarcoMue** [comment]
I cant reproduce my own findings anymore, so i guess i did a mistake with my initial setup.
I close this.
